# Generated by Django 5.2.12 on 2026-03-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.CharField(max_length=50)),
                ('raw_prompt', models.TextField()),
                ('llm_reasoning', models.TextField(help_text='General LLM answer from the building instructions')),
                ('action_playload', models.TextField(help_text='Specific Minecraft commands to build based on the responses from general instructions')),
                ('task_type', models.CharField(default='building', max_length=20)),
            ],
            options={
                'verbose_name': 'Agent Task',
                'verbose_name_plural': 'Agent Tasks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
