# Generated by Django 5.2.12 on 2026-03-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agentinteraction',
            name='player_id',
        ),
        migrations.AddField(
            model_name='agentinteraction',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='bot.player'),
        ),
    ]
