# Generated by Django 5.2.12 on 2026-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_player_remove_agentinteraction_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(blank=True, choices=[('B', 'Bot'), ('H', 'Human')], max_length=1, null=True),
        ),
    ]
