# Generated by Django 5.2.12 on 2026-03-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_player_player_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentinteraction',
            old_name='action_playload',
            new_name='action_payload',
        ),
    ]
