# Generated by Django 5.2.12 on 2026-03-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_action_playload_agentinteraction_action_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinteraction',
            name='action_payload',
            field=models.TextField(blank=True, help_text='Specific Minecraft commands to build based on the responses from general instructions', null=True),
        ),
        migrations.AlterField(
            model_name='agentinteraction',
            name='llm_reasoning',
            field=models.TextField(blank=True, help_text='General LLM answer from the building instructions', null=True),
        ),
    ]
