# Generated by Django 5.2.12 on 2026-04-07 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_action_playload_agentinteraction_action_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinteraction',
            name='action_payload',
            field=models.TextField(blank=True, help_text='Specific Minecraft commands to build based on the responses from general instructions', null=True),
        ),
        migrations.AlterField(
            model_name='agentinteraction',
            name='llm_reasoning',
            field=models.TextField(blank=True, help_text='General LLM answer from the building instructions', null=True),
        ),
        migrations.CreateModel(
            name='postChatMessagesSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bot.player')),
            ],
            options={
                'verbose_name': 'postChatMessages Session',
                'verbose_name_plural': 'postChatMessages Sessions',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='postChatMessagesMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.postChatMessagessession')),
            ],
            options={
                'verbose_name': 'postChatMessages Message',
                'verbose_name_plural': 'postChatMessages Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
