# Generated by Django 5.2.12 on 2026-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_postchatmessagessession_player_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
