# Generated by Django 5.2.12 on 2026-04-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_chatmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='bot_persona',
        ),
        migrations.RemoveField(
            model_name='chatmessages',
            name='session_id',
        ),
    ]
