# Generated by Django 5.2.12 on 2026-04-25 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_chatsession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
